name: gpu-tests

on: workflow_dispatch

jobs:
  gpu-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure aws
        run: |
          aws configure set aws_access_key_id ${{ secrets.DEV_AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.DEV_AWS_SECRET_KEY }}
          aws configure set default.region us-east-1

      - name: Install & check skypilot configuration
        run: |
          python -m pip install --upgrade pip
          pip install skypilot
          sky check
          sky status

      - name: Install python packages & dependencies
        run: |
          pip install runhouse pytest tqdm datasets

      - name: Run all gpu tests
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: pytest -v -k "gputest"

      - name: Teardown all gpu clusters
        run: |
          sky status
          sky down --all -y
          sky status
